# Generated by Django 5.0.6 on 2024-08-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_band_situation'),
        ('listings', '0008_listing_town_name'),
    ]

    operations = [
    ]
