# Generated by Django 5.0.6 on 2024-08-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_merge_0008_band_situation_0008_listing_town_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='situation',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='town_name',
        ),
    ]
